import { ThemeProvider } from "@/components/providers/theme-provider"
import "@/style/globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import font from "next/font/local"

const inter = Inter({
  subsets: ["latin"],
})

const acorn = font({
  src: "../public/fonts/acorn.woff",
  variable: "--font-acorn",
  weight: "600",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} ${acorn.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
